### ISSUE TITLE
Undefined node elif

### ISSUE THREAD

**Issue by hiskuDN** [jspython-dev/jspython#21]
I'm trying to parse a python code into an AST but every time I add an elif statement, it gives me the following error:
![image](https://user-images.githubusercontent.com/18376750/115183344-8fde6000-a116-11eb-9cf1-0cad5ab4d936.png)
Thanks for the help!

**Comment by ppaska** [comment]
elif still not implemented. We have ticket #3

**Comment by justamirror** [comment]
close this there's already a ticket no need for a second one

**Comment by ppaska** [comment]
released v2.1.12
