### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by yalondpsi** [jspython-dev/jspython#32]
Hi
When there is an error in a user's "python" program, is there a way to capture does errors?
Maybe by error codes?
I want to return to the user a custom error message
Thank you

**Comment by ppaska** [comment]
There is no need for error codes.
Error handling is a very important part of this project and so far works perfectly well.

So, if your JSPython is incorrect it should show you the exact line where the problem is.

How are you using it? eval, evalAsync? Please describe your scenario in more detail. Then, we can suggest you a solution

**Comment by yalondpsi** [comment]
Hi @ppaska 
Maybe I did not explain myself - There is no problem with JSPython error messages, 
I need to present the user a custom error message - in a language which is not English.
I did not start using it yet
I want to use JSPython with ace editor
I need to present to the user **a modal window with the error and line number** :)
Thanks

**Comment by yalondpsi** [comment]
@ppaska 
There is a typo in the page:
https://www.jspython.dev/docs/jspython-interpreter

![image](https://user-images.githubusercontent.com/14073961/180775412-82a22bf9-5df9-448c-8f04-1f6d05495e9c.png)

**Comment by yalondpsi** [comment]
@ppaska 
I run this code with an error inside, how do I get the error's line number?

`<script async type="module">

const jsPython = window.jspython.jsPython;
const script = `
  x = 2 + 3 + a
  x
`;

const interpreter = jsPython();
try {
    const res = await interpreter.evaluate(script);
    console.table(res); 

} catch(err) {
    console.log("error:");
    console.error(err.message)
}
</script>`

**Comment by ppaska** [comment]
in the message you have line number

**Comment by ppaska** [comment]
> @ppaska I run this code with an error inside, how do I get the error's line number?
> 
> `<script async type="module">
> 
> const jsPython = window.jspython.jsPython; const script = `x = 2 + 3 + a x`;
> 
> const interpreter = jsPython(); try { const res = await interpreter.evaluate(script); console.table(res);
> 
> } catch(err) { console.log("error:"); console.error(err.message) } </script>`

You will get the line number in the error message

**Comment by ppaska** [comment]
> @ppaska There is a typo in the page: https://www.jspython.dev/docs/jspython-interpreter
> 
> ![image](https://user-images.githubusercontent.com/14073961/180775412-82a22bf9-5df9-448c-8f04-1f6d05495e9c.png)

evaluate(script)).then(res => console.log(res), e => console.error(e))

**Comment by yalondpsi** [comment]
I saw the line number as part of the string, whould it be more comfort to reveal an object { error_msg: '', line: 2, error_code: 0 } ?

**Comment by ppaska** [comment]
no plans to change it anytime soon

**Comment by yalondpsi** [comment]
> no plans to change it anytime soon

Thank you for the great help
