### ISSUE TITLE
jsPython isn't defined

### ISSUE THREAD

**Issue by Saswat689** [jspython-dev/jspython#36]
I am trying to use this library for parsing python and then displaying the result on web page client side.

I am importing it via cdn inside head described in docs

and then running this code in my script at the end of body

` jsPython()
    .evaluate('print("Hello World!")')
    .then(
        r => console.log("Result => ", r),
        e => console.log("Error => ", error)
    )`

It says jsPython is undefined

**Comment by ppaska** [comment]
```
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jspython-interpreter/dist/jspython-interpreter.min.js">
</script>

<script>
	jspython
	.jsPython().evaluate('print("Hello World!")')
		.then(
			r => console.log("Result => ", r),
			e => console.log("Error => ", error)
		)
</script>
</head>
<body></body>
</html>
```
