### ISSUE TITLE
Object key iteration does not work

### ISSUE THREAD

**Issue by jumangee** [jspython-dev/jspython#38]
example:
```
v = {"test":1,"2":2}

for t in v:
    print(t)
```
Outputs nothing

But www.online-python.com produces:
```
test
2
```

Is it ok or bug? (I am not very familiar with the syntax of the python)

**Comment by ppaska** [comment]
It shouldn't work. You can iterate only arrays. Try using Object.keys

```python
v = {"test":1,"2":2}

for t in Object.keys(v):
    print(t)
```

**Comment by jumangee** [comment]
@ppaska sorry, but why? :)
![изображение](https://github.com/jspython-dev/jspython/assets/3863733/21062b7a-9777-4001-8128-d54bae8ca2d3)
![изображение](https://github.com/jspython-dev/jspython/assets/3863733/9bffff98-252b-4025-b31c-5b6e70ea2c3a)
